### ISSUE TITLE
Delete actor

### ISSUE THREAD

**Issue by JvGinkel** [biokoda/actordb#4] opened 2015-04-15 13:34 UTC
Hi,

I hope you can help me explain how to do the following.

I have created a new actorType in the schema.yaml and then created a new actor with this type and a id. I have done some testing and now I want to remove this actor with this id. How can I do this?

mysql> ACTOR accounting(test) CREATE;
Query OK, 0 rows affected (0.00 sec)

mysql> show tables;
+----------------+
| name           |
+----------------+
| __transactions |
| __adb          |
| accounting     |
+----------------+
3 rows in set (0.01 sec)

mysql> select * FROM accounting;
Empty set (0.00 sec)

This is working fine. But how do I remove "test"? When I try the following:
mysql> ACTOR accounting(test); PRAGMA delete;
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

mysql> show tables;
+----------------+
| name           |
+----------------+
| __transactions |
| __adb          |
| accounting     |
+----------------+
3 rows in set (0.00 sec)

There is still a accounting table for "test".

**Comment by SergejJurecko** [comment] 2015-04-15 14:09
What actordb version are you using?

**Comment by SergejJurecko** [comment] 2015-04-15 14:37
Right I see where the problem is. This is actually just a problem with mysql console. Pragma statements involve special handling and so does mysql console. I will look into fixing it. 

In the meanwhile you can run queries a different way (without writing code). Run: actordb attach, then to execute a statement run: actordb:exec("ACTOR accounting(test) CREATE; select * from accounting;").

**Comment by JvGinkel** [comment] 2015-04-15 19:45
Maybe I miss understand you but:
(fe1@fe1)1> actordb:exec("ACTOR accounting(*); PRAGMA list;")
(fe1@fe1)1> actordb:exec("ACTOR accounting(*); PRAGMA list;")
(fe1@fe1)1> actordb:exec("ACTOR accounting(*); PRAGMA exists;") 
(fe1@fe1)1>
None of them seems to work. Or do I something wrong?

**Comment by djustinek** [comment] 2015-04-15 20:20
@JvGinkel: From what you have written, there is a problem in your Erlang syntax. Each command has to have a closing period, like this:
```
actordb:exec("ACTOR accounting(*); PRAGMA list;"). % don't forget the period at the end
```


Maybe you can join us on ActorDB Facebook Group and we can help you out there: https://www.facebook.com/groups/actordb/

**Comment by JvGinkel** [comment] 2015-04-15 20:30
@djustinek Thanks for the example. Its working now! And I joined your FB group to.

**Closed** 2015-11-19 18:03 UTC
